name: check for changed file

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  check-for-changed-file:
    runs-on: ubuntu-latest     

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Did index.md change?
        id: changed-index-file
        uses: tj-actions/changed-files@v38
        with:
          files: docs/index.md
      

      # - name: Create issue if index.md changed
      #   if: steps.changed-index-file.outputs.any_changed == 'true'
      #   uses: JasonEtco/create-an-issue@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     filename: .github/ISSUE_TEMPLATE/file-changed.md
      #     update_existing: true

      - name: Get sha
        if: steps.changed-index-file.outputs.any_changed == 'true'
        run: |
          echo 'FILE_SHA='(git log -n 1 --pretty=format:%H -- docs/index.md) >> $GITHUB_ENV

      - name: Create issue with gh
        if: steps.changed-index-file.outputs.any_changed == 'true'
        run: gh issue create --title "New Issue report" --body "The index.md file changed with latest push $FILE_SHA. Review and update." --assignee MonicaG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}