name: on-push workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      deploy_location:
        description: 'Deploy to'
        required: true
        default: dev
        type: choice
        options:
        - dev
        - prod  

jobs:
  check-for-changed-file:
    runs-on: ubuntu-latest     

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Ran from push to prod
        run: |
            echo "Should always run"    

      - name: Ran from workflow dispatch - prod
        # Only publish to prod when triggered to do so
        if: ${{ github.event_name == 'workflow_dispatch' }} 
        run: |
          echo "Workflow dispatch prod"

      # - name: Ran from workflow dispatch - dev
      #   if: ${{ github.event_name == 'workflow_dispatch' }} && ${{ inputs.deploy_location == 'dev' }} 
      #   run: |
      #     echo "Workflow dispatch dev"
